create table if not exists public.portfolio_analytics (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null check (event_type in ('session_start', 'section_view', 'project_view', 'video_play')),
  section_id text,
  project_slot text,
  project_title text,
  project_group text,
  page_path text,
  page_hash text,
  referrer_host text,
  device_type text,
  os_name text,
  browser_name text,
  viewport_width integer,
  viewport_height integer,
  language text,
  timezone text,
  country_code text,
  region_name text,
  region_code text,
  city_name text,
  network_org text,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_analytics_created_at_idx on public.portfolio_analytics (created_at desc);
create index if not exists portfolio_analytics_event_type_idx on public.portfolio_analytics (event_type, created_at desc);
create index if not exists portfolio_analytics_session_idx on public.portfolio_analytics (session_id, created_at desc);

alter table public.portfolio_analytics enable row level security;
revoke all on public.portfolio_analytics from anon, authenticated;

create or replace function public.record_portfolio_event(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  kind text := left(coalesce(payload->>'event_type', ''), 40);
  sid text := left(coalesce(payload->>'session_id', ''), 100);
begin
  if kind not in ('session_start', 'section_view', 'project_view', 'video_play') or sid = '' then
    raise exception 'invalid analytics event';
  end if;

  insert into public.portfolio_analytics (
    session_id, event_type, section_id, project_slot, project_title, project_group,
    page_path, page_hash, referrer_host, device_type, os_name, browser_name,
    viewport_width, viewport_height, language, timezone, country_code,
    region_name, region_code, city_name, network_org
  ) values (
    sid,
    kind,
    nullif(left(coalesce(payload->>'section_id', ''), 80), ''),
    nullif(left(coalesce(payload->>'project_slot', ''), 160), ''),
    nullif(left(coalesce(payload->>'project_title', ''), 240), ''),
    nullif(left(coalesce(payload->>'project_group', ''), 40), ''),
    nullif(left(coalesce(payload->>'page_path', ''), 300), ''),
    nullif(left(coalesce(payload->>'page_hash', ''), 120), ''),
    nullif(left(coalesce(payload->>'referrer_host', ''), 200), ''),
    nullif(left(coalesce(payload->>'device_type', ''), 40), ''),
    nullif(left(coalesce(payload->>'os_name', ''), 60), ''),
    nullif(left(coalesce(payload->>'browser_name', ''), 60), ''),
    case when (payload->>'viewport_width') ~ '^[0-9]{1,5}$' then (payload->>'viewport_width')::integer end,
    case when (payload->>'viewport_height') ~ '^[0-9]{1,5}$' then (payload->>'viewport_height')::integer end,
    nullif(left(coalesce(payload->>'language', ''), 30), ''),
    nullif(left(coalesce(payload->>'timezone', ''), 80), ''),
    nullif(left(coalesce(payload->>'country_code', ''), 8), ''),
    nullif(left(coalesce(payload->>'region_name', ''), 120), ''),
    nullif(left(coalesce(payload->>'region_code', ''), 20), ''),
    nullif(left(coalesce(payload->>'city_name', ''), 120), ''),
    nullif(left(coalesce(payload->>'network_org', ''), 180), '')
  );
end;
$$;

revoke all on function public.record_portfolio_event(jsonb) from public;
grant execute on function public.record_portfolio_event(jsonb) to anon, authenticated;

create or replace view public.analytics_visit_overview as
select
  date_trunc('day', created_at at time zone 'Asia/Shanghai')::date as visit_date,
  count(*) as visits,
  count(distinct session_id) as sessions
from public.portfolio_analytics
where event_type = 'session_start'
group by 1
order by 1 desc;

create or replace view public.analytics_project_views as
select
  project_group,
  project_title,
  count(*) filter (where event_type = 'project_view') as opens,
  count(distinct session_id) filter (where event_type = 'project_view') as unique_sessions,
  count(distinct session_id) filter (where event_type = 'video_play') as video_play_sessions,
  max(created_at) as last_seen_at
from public.portfolio_analytics
where event_type in ('project_view', 'video_play')
group by project_group, project_title
order by opens desc, last_seen_at desc;

create or replace view public.analytics_device_summary as
select device_type, os_name, browser_name, count(*) as visits, count(distinct session_id) as sessions
from public.portfolio_analytics
where event_type = 'session_start'
group by device_type, os_name, browser_name
order by visits desc;

create or replace view public.analytics_location_summary as
select country_code, region_name, region_code, city_name, network_org, count(*) as visits, count(distinct session_id) as sessions
from public.portfolio_analytics
where event_type = 'session_start'
group by country_code, region_name, region_code, city_name, network_org
order by visits desc;

create or replace view public.analytics_section_views as
select section_id, count(*) as views, count(distinct session_id) as unique_sessions, max(created_at) as last_seen_at
from public.portfolio_analytics
where event_type = 'section_view'
group by section_id
order by views desc;

revoke all on public.analytics_visit_overview from anon, authenticated;
revoke all on public.analytics_project_views from anon, authenticated;
revoke all on public.analytics_device_summary from anon, authenticated;
revoke all on public.analytics_location_summary from anon, authenticated;
revoke all on public.analytics_section_views from anon, authenticated;
