import React,{useEffect,useRef,useState} from 'react'
import{createRoot}from'react-dom/client'
import Aurora from './Aurora'
import PillNav from './PillNav'
import{gsap}from'gsap'
import{ScrollTrigger}from'gsap/ScrollTrigger'
import'./styles.css'
gsap.registerPlugin(ScrollTrigger)

const Arrow=({down=false})=><svg viewBox="0 0 24 24" aria-hidden="true"><path d={down?'M12 4v15m0 0 6-6m-6 6-6-6':'M5 19 19 5m0 0H8m11 0v11'}/></svg>
const initialProjects=[
 {id:'01',type:'商业项目',title:'快影 × App Store',desc:'动态 Banner 系列',meta:'Motion / Visual / 2026',tone:'lime',slot:'project-0'},
 {id:'02',type:'MG 动画',title:'视听节奏实验',desc:'图形、节奏与叙事',meta:'MG Animation / 2025',tone:'blue',slot:'project-1'},
 {id:'03',type:'AI 提效案例',title:'生成式工作流',desc:'从批量素材到动效交付',meta:'AIGC / Vibe Coding',tone:'violet',slot:'project-2'},
 {id:'04',type:'商业动销',title:'模板与特效设计',desc:'高考热点文字模板',meta:'Campaign / 2026',tone:'orange',slot:'project-3'},
]
const capabilities=[['01','Motion System','AE / MG 动画 / 粒子特效 / Mocha 跟踪 / 二维人物绑定'],['02','Commercial Sense','真实短视频平台经验，从热点洞察、创意设计到上线交付。'],['03','AIGC Workflow','AI 图像与视频生成结合后期包装，让创意更快抵达成片。'],['04','Toolmaker Mindset','用 Vibe Coding 拆解重复工作，搭建轻量工具提升效率。']]
const experiences=[['2026.03 — 2026.09','深圳市快手技术有限公司','动效设计师 / 快影业务'],['2023 — 2027','阳光学院','数字媒体技术 / 本科'],['NOW','持续探索','AIGC 商业动效与效率工具']]
const initialCoreProjects=[
 { ...initialProjects[0], slot:'core-0', title:'快影商业动效项目', category:'商业项目', year:'2026', detail:'对接平面设计师与运营，完成 App Store 动态 Banner、品牌动效编排、节奏控制与上线交付。项目覆盖文字、人物、画面特效与转场等多种商业场景。' },
 { ...initialProjects[2], slot:'core-1', title:'AIGC 创意试手', category:'AI 商业落地', year:'2026', detail:'结合 AI 视频生成能力制作符合短视频平台调性的口播与人物素材，并完成文字、特效、节奏和画面包装，形成从生成到交付的完整链路。' },
 { ...initialProjects[3], slot:'core-2', title:'高考热点文字模板', category:'动态模板设计', year:'2026', detail:'从热点洞察与用户情绪出发设计文字模板，精准匹配使用场景，打破快影 App 文字模板销量与使用纪录。' }
]

const PROJECTS_KEY='fsw-portfolio-projects-v1',CORE_KEY='fsw-portfolio-core-v1',MEDIA_DB='fsw-portfolio-media-v1'
const readSaved=(key,fallback)=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
const openMediaDB=()=>new Promise((resolve,reject)=>{const request=indexedDB.open(MEDIA_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('media',{keyPath:'slot'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
const saveMediaBlob=async(slot,file)=>{const db=await openMediaDB();await new Promise((resolve,reject)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').put({slot,file,name:file.name,type:file.type});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
const loadMediaBlobs=async()=>{const db=await openMediaDB();const rows=await new Promise((resolve,reject)=>{const request=db.transaction('media').objectStore('media').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return rows}
const clearMediaBlobs=async()=>{const db=await openMediaDB();await new Promise((resolve,reject)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}

function useMotion(deps=[]){useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(x=>x.classList.add('visible'));return}const ctx=gsap.context(()=>{gsap.timeline({defaults:{ease:'power4.out'}}).fromTo('.opening-curtain__panel',{scaleY:1},{scaleY:0,duration:1.4,stagger:.08,transformOrigin:'top'},0).fromTo('.hero-center h1',{y:110,scaleX:.72,clipPath:'inset(100% 0 0 0)'},{y:0,scaleX:1,clipPath:'inset(0% 0 0 0)',duration:1.55},.32).fromTo('.hero-center>small,.hero-center>p,.hero-meta,.hero-center blockquote,.explore-btn',{y:34,opacity:0},{y:0,opacity:1,duration:1,stagger:.11},.72).to('.opening-curtain',{autoAlpha:0,duration:.45},1.3);['#about','#work','#gallery','#abilities','#contact'].forEach(id=>{const section=document.querySelector(id);if(!section)return;const title=section.querySelector('h2');if(title)gsap.fromTo(title,{y:110,scaleY:.68,clipPath:'inset(100% 0 0 0)'},{y:0,scaleY:1,clipPath:'inset(0% 0 0 0)',duration:1.35,ease:'power4.out',scrollTrigger:{trigger:section,start:'top 78%',once:true}});const items=section.querySelectorAll('.portrait,.about-copy,.timeline-item,.core-row,.mosaic-item,.cap-card,.tools,.contact-inner>p,.contact-inner>a');if(items.length)gsap.fromTo(items,{y:60,opacity:0},{y:0,opacity:1,duration:1.1,stagger:.09,ease:'power3.out',scrollTrigger:{trigger:section,start:'top 70%',once:true}})});gsap.utils.toArray('.portrait img,.core-preview-media img,.mosaic-item img').forEach(img=>gsap.fromTo(img,{yPercent:-4},{yPercent:4,ease:'none',scrollTrigger:{trigger:img,start:'top bottom',end:'bottom top',scrub:1.2}}))});const move=e=>{const card=e.target.closest?.('.glow-card');document.querySelectorAll('.glow-card.is-glowing').forEach(x=>{if(x!==card)x.classList.remove('is-glowing')});if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${e.clientX-r.left}px`);card.style.setProperty('--my',`${e.clientY-r.top}px`);card.classList.add('is-glowing')};document.addEventListener('pointermove',move,{passive:true});return()=>{ctx.revert();document.removeEventListener('pointermove',move)}},deps)}
function useAnimatedContentSystem(){useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));return}const ctx=gsap.context(()=>{
 gsap.set('.reveal',{opacity:1,y:0});
 const opening=gsap.timeline({defaults:{ease:'power3.out'}});
 opening.fromTo('.opening-curtain__panel',{scaleY:1},{scaleY:0,duration:.42,stagger:.025,transformOrigin:'top'},0)
  .fromTo('.hero-center h1,.hero-center>small',{y:42,opacity:0},{y:0,opacity:1,duration:.34,stagger:.035},.12)
  .fromTo('.hero-center>p,.hero-meta,.hero-center blockquote',{y:24,opacity:0},{y:0,opacity:1,duration:.28,stagger:.035},.3)
  .fromTo('.explore-btn',{y:18,opacity:0},{y:0,opacity:1,duration:.24},.5)
  .to('.opening-curtain',{autoAlpha:0,duration:.18},.62);
 const groups=[
  {section:'#about',title:'.about-title',description:'.about-copy',cards:'.portrait,.timeline-item'},
  {section:'#work',title:'.core-heading>div',description:'.core-heading>p',cards:'.core-row',start:'top 78%'},
  {section:'#gallery',title:'.work-head .section-tag,.work-head h2',description:'.work-head>p',cards:'.mosaic-item'},
  {section:'#abilities',title:'.abilities-head',cards:'.cap-card,.tools'},
  {section:'#contact',title:'.contact-inner>.section-tag',description:'.contact-inner>p',buttons:'.contact-inner>a',cards:'.contact-bottom'}
 ];
groups.forEach(({section,title,description,buttons,cards,start='top 82%'})=>{const root=document.querySelector(section);if(!root)return;const titleEls=gsap.utils.toArray(root.querySelectorAll(title||':not(*)'));const descriptionEls=gsap.utils.toArray(root.querySelectorAll(description||':not(*)'));const buttonEls=gsap.utils.toArray(root.querySelectorAll(buttons||':not(*)'));const cardEls=gsap.utils.toArray(root.querySelectorAll(cards||':not(*)'));const cardStagger=cardEls.length>1?Math.min(.045,.2/(cardEls.length-1)):.01;const allEls=[...titleEls,...descriptionEls,...buttonEls,...cardEls];let started=false;const startTimeline=()=>{if(started)return;started=true;const tl=gsap.timeline({defaults:{ease:'power3.out'},onComplete:()=>gsap.set(allEls,{clearProps:'transform,opacity,visibility'})});if(titleEls.length)tl.fromTo(titleEls,{x:-32,opacity:0},{x:0,opacity:1,duration:.28,stagger:.025},0);if(descriptionEls.length)tl.fromTo(descriptionEls,{y:20,opacity:0},{y:0,opacity:1,duration:.24,stagger:.025},.16);if(buttonEls.length)tl.fromTo(buttonEls,{y:16,opacity:0},{y:0,opacity:1,duration:.22,stagger:.025},.3);if(cardEls.length)tl.fromTo(cardEls,{y:24,opacity:0},{y:0,opacity:1,duration:.34,stagger:cardStagger},.42)};ScrollTrigger.create({trigger:root,start,once:true,onEnter:startTimeline});if(location.hash===section)startTimeline();else requestAnimationFrame(()=>requestAnimationFrame(()=>{const rect=root.getBoundingClientRect();if(rect.top<innerHeight*.9&&rect.bottom>0)startTimeline()}))})
 });return()=>ctx.revert()},[])}
function useGlow(deps=[]){useEffect(()=>{const cards=document.querySelectorAll('.portrait,.core-preview-media,.mosaic-item,.cap-card,.timeline-item');cards.forEach(x=>x.classList.add('glow-card'));return()=>cards.forEach(x=>x.classList.remove('glow-card'))},deps)}
function Media({src,type,className='',children}){if(!src)return <div className={`media-placeholder ${className}`}>{children}</div>;return type?.startsWith('video')?<video className={className} src={src} autoPlay muted loop playsInline/>:<img className={className} src={src} alt="自定义作品素材"/>}

function App(){
 const[studio,setStudio]=useState(false),[media,setMedia]=useState({}),[projects,setProjects]=useState(()=>readSaved(PROJECTS_KEY,initialProjects)),[coreItems,setCoreItems]=useState(()=>readSaved(CORE_KEY,initialCoreProjects)),[hoveredCore,setHoveredCore]=useState(null),[detail,setDetail]=useState(null)
 const urls=useRef([]);useAnimatedContentSystem();useGlow([projects.length,coreItems.length]);useEffect(()=>{loadMediaBlobs().then(rows=>{const restored={};rows.forEach(({slot,file,name,type})=>{const src=URL.createObjectURL(file);urls.current.push(src);restored[slot]={src,type,name}});setMedia(restored)}).catch(()=>{});return()=>urls.current.forEach(URL.revokeObjectURL)},[])
 useEffect(()=>{localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects))},[projects])
 useEffect(()=>{localStorage.setItem(CORE_KEY,JSON.stringify(coreItems))},[coreItems])
 useEffect(()=>{document.body.style.overflow=detail?'hidden':'';const close=e=>e.key==='Escape'&&setDetail(null);window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[detail])
 const upload=(slot,file)=>{if(!file)return;const url=URL.createObjectURL(file);urls.current.push(url);setMedia(m=>({...m,[slot]:{src:url,type:file.type,name:file.name}}));saveMediaBlob(slot,file).catch(()=>{})}
 const addProjects=files=>{[...files].forEach(file=>{const slot=`project-${Date.now()}-${Math.random()}`,url=URL.createObjectURL(file);urls.current.push(url);setProjects(ps=>{const id=String(ps.length+1).padStart(2,'0');return[...ps,{id,type:'新增作品',title:file.name.replace(/\.[^.]+$/,''),desc:'点击素材管理可继续替换',meta:'New project',tone:['lime','blue','violet','orange'][ps.length%4],slot}]});setMedia(m=>({...m,[slot]:{src:url,type:file.type,name:file.name}}));saveMediaBlob(slot,file).catch(()=>{})})}
 const addCore=()=>setCoreItems(items=>[...items,{id:String(items.length+1).padStart(2,'0'),type:'核心项目',title:`新核心项目 ${items.length+1}`,category:'自定义分类',year:'2026',detail:'点击项目后可编辑文字说明。',meta:'Core project',tone:['lime','blue','violet','orange'][items.length%4],slot:`core-${Date.now()}`}])
 const removeCore=index=>setCoreItems(items=>items.filter((_,i)=>i!==index).map((x,i)=>({...x,id:String(i+1).padStart(2,'0')})))
 const updateItem=(source,index,field,value)=>{const setter=source==='core'?setCoreItems:setProjects;setter(items=>items.map((item,i)=>i===index?{...item,[field]:value}:item));setDetail(d=>d&&d.source===source&&d.index===index?{...d,[field]:value}:d)}
 const resetAll=()=>{urls.current.forEach(URL.revokeObjectURL);urls.current=[];setMedia({});setProjects(initialProjects);setCoreItems(initialCoreProjects);localStorage.removeItem(PROJECTS_KEY);localStorage.removeItem(CORE_KEY);clearMediaBlobs().catch(()=>{})}
 return <>
 <div className="opening-curtain" aria-hidden="true"><i className="opening-curtain__panel"/><i className="opening-curtain__panel"/><i className="opening-curtain__panel"/></div>
 <div className="global-aurora"><Aurora colorStops={['#7cff67','#8e62ff','#1623ff']} blend={.48} amplitude={1.25} speed={.42}/></div>
 <header className="nav shell"><a href="#top" className="brand"><i/>FSW<span>®</span></a><span className="nav-role">MOTION · VISUAL · AIGC</span><div className="nav-actions"><button type="button" aria-label="打开素材管理" className="studio-btn" onClick={()=>setStudio(true)}>素材管理</button><a className="contact-pill" href="#contact">联系我 <Arrow/></a></div></header>
 <main id="top">
  <section className="hero"><div className="hero-content shell"><div className="eyebrow"><span>PORTFOLIO · 2026</span><span>SHENZHEN / CHINA</span></div><div className="hero-center"><small>MOTION & VISUAL PORTFOLIO</small><h1>范殊玮 <span>/ FAN SHUWEI</span></h1><p>二维动效设计师 · 视觉设计师 · AIGC 商业动销设计师</p><div className="hero-meta"><a href="mailto:1620116392@qq.com">✉ 1620116392@qq.com</a><a href="tel:17670905513">⌕ 176 7090 5513</a><span>✦ AE · MG · AIGC · VIBE CODING</span></div><blockquote>“让每一帧服务于信息，也保留属于画面的情绪。”</blockquote><a href="#work" className="explore-btn">EXPLORE WORK <Arrow down/></a></div></div><PillNav items={[{label:'个人简介',href:'#about'},{label:'精选项目',href:'#work'},{label:'个人优势',href:'#abilities'},{label:'联系方式',href:'#contact'}]}/></section>
  <section id="about" className="about section shell"><div className="about-title reveal"><div><h2>WORK EXPERIENCE <b>↘</b></h2><span>个人经历 / ABOUT ME</span></div><span>[ 01 / ABOUT ]</span></div><div className="about-showcase"><div className="portrait reveal"><Media {...media.avatar}><span>YOUR<br/>PORTRAIT</span><small>支持 JPG / PNG / WEBP</small></Media><b>FAN SHUWEI</b></div><div className="about-copy reveal"><small>ABOUT ME</small><h3>Hi, I am <em>Fan Shuwei!</em></h3><p>我是一名二维动效与视觉设计师，把节奏、叙事与商业目标装进每一帧。具备快手真实项目经验，也持续用 AIGC 与轻量工具拓展创作效率。</p><div className="info-grid"><div><small>求职方向</small><strong>Motion / Visual / AIGC</strong></div><div><small>工作经验</small><strong>快手 · 快影业务</strong></div><div><small>电话</small><strong>176 7090 5513</strong></div><div><small>邮箱</small><strong>1620116392@qq.com</strong></div></div><div className="about-numbers"><div><b>200+</b><span>商业素材交付</span></div><div><b>60+</b><span>S 级评级素材</span></div><div className="record"><b>NO.1</b><span>文字模板打破快影 App 销量纪录</span></div></div><div className="now-building"><small>NOW BUILDING</small><span>商业动效</span><span>AIGC 工作流</span><span>视觉设计系统</span></div></div></div><div className="timeline reveal">{experiences.map((e,i)=><div className="timeline-item" key={e[0]}><i/><small>{e[0]}</small><h4>{e[1]}</h4><span>{e[2]}</span></div>)}</div></section>
  <section id="work" className="core-work section"><div className="shell core-heading reveal"><div><span>精选</span><h2>核心项目</h2><i/></div><p>这里是我的核心商业项目。<br/>悬停预览，点击查看完整作品与项目说明。</p></div><div className="core-list shell reveal">{coreItems.map((p,i)=><article className={`core-row ${hoveredCore===i?'is-open':''}`} key={p.slot} onMouseEnter={()=>setHoveredCore(i)} onMouseLeave={()=>setHoveredCore(null)}><button onClick={()=>setDetail({...p,source:'core',index:i})} aria-label={`查看核心项目：${p.title}`}><span>0{i+1}</span><h3>{p.title}</h3><div><small>{p.category}</small><small>{p.year}</small><b>↗</b></div></button><div className="core-preview" onClick={()=>setDetail({...p,source:'core',index:i})}><div className={`core-preview-media ${p.tone}`}><Media {...media[p.slot]}><div className="mosaic-art"><span>0{i+1}</span><strong>{p.title}</strong><i>点击查看完整项目</i></div></Media></div></div></article>)}</div></section>
  <section id="gallery" className="work section"><div className="shell work-head reveal"><div className="section-tag">[ 03 / PROJECT GALLERY ]</div><h2>项目画廊 <strong>PROJECT GALLERY</strong></h2><p>{projects.length} PROJECTS<br/>CLICK TO VIEW FULL</p></div><div className="project-mosaic shell reveal">{projects.map((p,i)=><button aria-label={`查看作品：${p.title}`} onClick={()=>setDetail({...p,category:p.type,year:p.meta,detail:p.desc,source:'gallery',index:i})} className={`mosaic-item item-${i%7} ${p.tone}`} key={p.slot}><Media {...media[p.slot]}><div className="mosaic-art"><span>{p.id}</span><strong>{p.type}</strong><i>{p.title}</i></div></Media><div className="mosaic-label"><div><small>{p.type} · {p.meta}</small><h3>{p.title}</h3></div><Arrow/></div></button>)}</div></section>
  <section id="abilities" className="abilities section shell"><div className="abilities-head reveal"><div className="section-tag">[ 03 / CAPABILITIES ]</div><h2>动效是方法，<br/><em>解决问题</em>才是目的。</h2></div><div className="cards">{capabilities.map(([n,t,d])=><article className="cap-card reveal" key={n}><span>{n}</span><div className="cap-icon">{n==='01'?'↗':n==='02'?'◉':n==='03'?'✦':'{}'}</div><h3>{t}</h3><p>{d}</p></article>)}</div><div className="tools reveal"><span>TOOLS & METHODS</span><div>AFTER EFFECTS · PHOTOSHOP · ILLUSTRATOR · C4D · MOCHA · AIGC · VIBE CODING</div></div></section>
  <section id="contact" className="contact"><div className="contact-glow"/><div className="shell contact-inner reveal"><div className="section-tag">[ 04 / LET'S TALK ]</div><p>有一个想法，或一段画面<br/>需要被赋予生命？</p><a href="mailto:1620116392@qq.com">LET'S MAKE IT <span>MOVE.</span> <Arrow/></a><div className="contact-bottom"><span>范殊玮 / MOTION & VISUAL DESIGNER</span><div><a href="tel:17670905513">176 7090 5513</a><a href="mailto:1620116392@qq.com">EMAIL</a><a href="#top">BACK TO TOP ↑</a></div></div></div></section>
 </main>
 <div className={`core-manager ${studio?'show':''}`}><strong>核心项目栏目</strong><button type="button" onClick={addCore}>＋ 新增栏目</button>{coreItems.map((x,i)=><button type="button" className="remove-core" onClick={()=>removeCore(i)} key={`remove-${x.slot}`}>删除 0{i+1}</button>)}</div>
 {detail&&<div className="project-detail" role="dialog" aria-modal="true" aria-label={`项目详情：${detail.title}`}><header><button onClick={()=>setDetail(null)} aria-label="关闭项目详情">←</button><div><h2>{detail.title}</h2><small>{detail.category||detail.type} / {detail.year||detail.meta}</small></div><span>PROJECT CASE</span></header><div className="detail-body"><div className={`detail-media ${detail.tone}`}><Media {...media[detail.slot]}><div className="mosaic-art"><span>{detail.id}</span><strong>{detail.title}</strong><i>{detail.category||detail.type}</i></div></Media></div><div className="detail-notes"><span>完整比例展示</span><span>支持图片 · 视频 · WebP</span></div><div className="detail-description"><label htmlFor="project-description">项目文字说明</label><textarea id="project-description" value={detail.detail??detail.desc??''} onChange={e=>updateItem(detail.source,detail.index,detail.source==='core'?'detail':'desc',e.target.value)} placeholder="在这里输入项目背景、设计思路、负责内容和最终成果……"/></div></div></div>}
 <aside className={`studio ${studio?'show':''}`} aria-hidden={!studio}><div className="studio-top"><div><small>LOCAL MEDIA STUDIO</small><h2>素材管理</h2></div><button aria-label="关闭素材管理" onClick={()=>setStudio(false)}>×</button></div><p>可编辑分类名称与项目名称。详情页中的文字说明也可以直接输入修改。</p><label className="upload"><span>个人头像 / 人物图<small>{media.avatar?.name||'JPG · PNG · WEBP'}</small></span><b>{media.avatar?'重新选择':'选择文件'}</b><input type="file" accept="image/*,.webp" onChange={e=>upload('avatar',e.target.files[0])}/></label><div className="upload-group-title"><span>CORE PROJECTS</span><b>核心项目</b></div>{coreItems.map((x,i)=><div className="project-editor" key={`core-${x.slot}`}><label><span>分类名称</span><input value={x.category} onChange={e=>updateItem('core',i,'category',e.target.value)}/></label><label><span>项目名称</span><input value={x.title} onChange={e=>updateItem('core',i,'title',e.target.value)}/></label><label className="upload core-upload"><span>0{i+1} · 项目素材<small>{media[x.slot]?.name||'MP4 · GIF · JPG · PNG · WEBP'}</small></span><b>{media[x.slot]?'重新选择':'上传作品'}</b><input type="file" accept="image/*,video/*,.gif,.webp" onChange={e=>upload(x.slot,e.target.files[0])}/></label></div>)}<div className="upload-group-title"><span>PROJECT GALLERY</span><b>项目画廊</b></div><label className="upload add"><span>新增多个作品<small>可一次选择多个文件</small></span><b>批量添加 +</b><input multiple type="file" accept="image/*,video/*,.gif,.webp" onChange={e=>addProjects(e.target.files)}/></label>{projects.map((x,i)=><div className="project-editor" key={`gallery-${x.slot}`}><label><span>分类名称</span><input value={x.type} onChange={e=>updateItem('gallery',i,'type',e.target.value)}/></label><label><span>项目名称</span><input value={x.title} onChange={e=>updateItem('gallery',i,'title',e.target.value)}/></label><label className="upload"><span>{x.id} · 项目素材<small>{media[x.slot]?.name||'MP4 · GIF · JPG · PNG · WEBP'}</small></span><b>{media[x.slot]?'重新选择':'选择文件'}</b><input type="file" accept="image/*,video/*,.gif,.webp" onChange={e=>upload(x.slot,e.target.files[0])}/></label></div>)}<button className="reset" onClick={()=>{setMedia({});setProjects(initialProjects);setCoreItems(initialCoreProjects)}}>恢复初始项目</button></aside><div className={`scrim ${studio?'show':''}`} onClick={()=>setStudio(false)}/>
 </>
}
createRoot(document.getElementById('root')).render(<App/>)
